# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Промодерирован'),
        ),
    ]
