# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20161208_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentStatus', verbose_name='Статус документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType', verbose_name='Тип документа'),
        ),
    ]
