# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('documents', '0005_auto_20161208_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.Comment', verbose_name='Комментарии'),
        ),
    ]
