# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='utilized',
            field=models.BooleanField(default=False, verbose_name='Списано'),
        ),
    ]
