# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarykind',
            options={'verbose_name': 'Вид библиотеки', 'verbose_name_plural': 'Виды библиотек'},
        ),
        migrations.AlterModelOptions(
            name='librarytype',
            options={'verbose_name': 'Тип библиотеки', 'verbose_name_plural': 'Типы библиотек'},
        ),
        migrations.AlterField(
            model_name='librarykind',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='librarytype',
            name='kinds',
            field=models.ManyToManyField(to='home.LibraryKind', verbose_name='Виды библиотек'),
        ),
        migrations.AlterField(
            model_name='librarytype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
