# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_cabinet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20161130_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
        migrations.AddField(
            model_name='library',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Администраторы'),
        ),
        migrations.AddField(
            model_name='library',
            name='reader_tickets',
            field=models.ManyToManyField(to='reader_cabinet.ReaderTicket', verbose_name='Читатели библиотеки'),
        ),
    ]
