# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161202_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='library',
            name='reader_tickets',
            field=models.ManyToManyField(blank=True, to='reader_cabinet.ReaderTicket', verbose_name='Читатели библиотеки'),
        ),
    ]
