# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('upload', models.FileField(upload_to=home.models.library_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='about',
            field=models.CharField(blank=True, max_length=255, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='library',
            name='bin',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='library',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='library',
            name='crr',
            field=models.CharField(blank=True, max_length=255, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='library',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='library',
            name='legal_entity_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (место нахождения) юридического лица'),
        ),
        migrations.AddField(
            model_name='library',
            name='legal_entity_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование юридического лица'),
        ),
        migrations.AddField(
            model_name='library',
            name='reservation_recommended_time',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Рекомендуемое время бронирования книги, дн.'),
        ),
        migrations.AddField(
            model_name='library',
            name='return_time_delay_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное время просрочки возврата документа, дн.'),
        ),
        migrations.AddField(
            model_name='librarydocument',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Library', verbose_name='Библиотека'),
        ),
    ]
