# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161207_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='reservation_recommended_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рекомендуемое время бронирования книги, дн.'),
        ),
    ]
