# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20161207_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarydocument',
            name='upload',
            field=models.FileField(upload_to=home.models.library_directory_path, verbose_name='Файл'),
        ),
    ]
