# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_auto_20161215_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryrequestaccess',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем одобрено'),
        ),
        migrations.AlterField(
            model_name='libraryrequestaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
